### ISSUE TITLE
Disable for a file?

### ISSUE THREAD

**Issue by Ryanauger95** [elixir-tesla/tesla#532]
I'm using an umbrella app and have `config :tesla, adapter: Tesla.Mock` set inside my config/test.exs. I use tesla throughout my apps, and need to do an actual call to an outside source (unmocked) in one test.

How can I disable mocking for an individual test file?

**Comment by yordis** [comment]
@Ryanauger95 normally, you call `Applicate.put_env` in the test case put the other client, and then put the old value back again.

```elixir
test "..." do
  Applicate.put_env(:tesla, :adapter, MyNewAdapter)
  # ....
  Applicate.put_env(:tesla, :adapter, Tesla.Mock)
end
```

I don't think the Tesla package could help you much here.

Being said that, I also have `Tesla` for multiple things, but the architecture of my code does not require such practices, so I am curious to know precisely how you set things up because the fix may require a bit of architectural change.

**Comment by alexandremcosta** [comment]
If you want to keep `async: true`, you can do

```elixir
Tesla.Mock.mock(fn env -> Tesla.Adapter.Hackney.call(env, []) end)
```
