### ISSUE TITLE
Tesla.Mock configuration

### ISSUE THREAD

**Issue by GGuinea** [elixir-tesla/tesla#561]
HI! 

What is the proper way to configure Tesla.Mock in situation described below.
Imagine we have a module which creates client:
```
defmodule SimpleApi.Client do
  @spec get_client() :: Tesla.Client.t()
  def get_client do
    middleware = [
      {Tesla.Middleware.BaseUrl, get_url()},
      Tesla.Middleware.EncodeJson
    ]
    adapter = {Tesla.Adapter.Finch, [name: MyFinch, recv_timeout: 40_000]}
    Tesla.client(middleware, adapter)
  end
end
```

To use mock in test, there is a need to configure it in test.exs
`
config :tesla, <instance_name>, adapter: Tesla.Mock
`
What should be placed in _<instance_name_?

BR

**Comment by teamon** [comment]
The config only works when you use the `use Tesla` macro. In your case when creating a dynamic client you need to pass the adapter from your own configuration.

```
adapter = Application.get_env(:myapp, :some_key) || {Tesla.Adapter.Finch, …}
```

and then configure the mock adapter in config/test.exs 

I usually put the default adapter in config/config.exs instead of directly in client module

**Comment by GGuinea** [comment]
Thank you @teamon. 
Using my own configuration works as expected.

All the best ;)
